# -*- coding: utf-8 -*-
"""Is_Victim_Term_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uyUzZk3o2kmv8iH90pUYU9A_EX8V9nnd

# Library
"""

# import sys
# !{sys.executable} -m pip install tensorflow-macos

import requests
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, classification_report
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import Ridge
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.decomposition import IncrementalPCA
import time
import tensorflow as tf
from tensorflow import keras
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

"""# Importing Dataset"""

# from google.colab import drive
# drive.mount('/content/drive')

df = pd.read_csv("final-Project.csv", on_bad_lines='skip')

"""# PreProcessing

## Initial Exploration

Before any processing, we inspect the structure of the dataset:
- Total rows and columns
- Column names and data types
- Missing value counts

The dataset is **bilingual** (English/French), containing duplicate columns
for most features. French-language duplicates will be removed in the next step.
"""

df.info()

df.isnull().sum()

df.dropna(inplace=True)
df.info()

df['Number of Victims / Nombre de victimes'] = df['Number of Victims / Nombre de victimes'].fillna(0).astype(int)
df['Dollar Loss /pertes financières'] = df['Dollar Loss /pertes financières'].replace({r'[$,]': ''}, regex=True).astype(float)
df

df.info()

df.columns

df = df.rename(columns={
    "Numéro d'identification / Number ID": "Number ID",
    "Date Received / Date reçue": "Date Received",
    "Victim Age Range / Tranche d'âge des victimes" : "Victim Age Range",
    "Number of Victims / Nombre de victimes":"Number of Victims",
    "Dollar Loss /pertes financières": "Dollar Loss"
})
display(df.head())

"""# Column Renaming
## Initial Exploration

Before any processing, we inspect the structure of the dataset:
- Total rows and columns
- Column names and data types
- Missing value counts

The dataset is **bilingual** (English/French), containing duplicate columns
for most features. French-language duplicates will be removed in the next step.
##  Column Renaming & Cleaning

Key columns are renamed for readability. French-language duplicate columns
(`Pays`, `Genre`, `Type de plainte`, etc.) are dropped, as they carry
identical information to their English counterparts.

The `Victim Age Range` column contains a leading apostrophe artifact (`'30 - 39`)
which is cleaned using `str.lstrip()`.

"""

columns_to_drop = [
    'Pays',
    'Genre',
    'Type de plainte',
    'Province/État',
    'Catégories thématiques sur la fraude et la cybercriminalité',
    'Langue de correspondance',
    'Méthode de sollicitation',
    'Type de plainte reçue'
]

existing_columns_to_drop = [col for col in columns_to_drop if col in df.columns]
df = df.drop(columns=existing_columns_to_drop)

display(df.columns)

df['Victim Age Range'] = df['Victim Age Range'].str.lstrip("' ")

df

df.info()

df.describe()

"""## Exploratory Data Analysis (EDA)

This section visualizes the key distributions and relationships in the dataset
to understand patterns before building models.

Charts included:
1. Distribution of Dollar Loss
2. Cases by Province/State
3. Victim Age Range distribution
4. Solicitation Method breakdown
5. Top Complaint Types
6. Dollar Loss by Age Range (Boxplot)
7. Correlation Heatmap
8. Number of Victims vs Dollar Loss (Scatter)
"""

# ===== 1. Dollar Loss Distribution =====
plt.figure(figsize=(10,4))
df['Dollar Loss'].dropna().hist(bins=50)
plt.title('Distribution of Dollar Loss')
plt.xlabel('Dollar Loss')
plt.show()

# ===== 2. Top Provinces =====
df['Province/State'].value_counts().head(10).plot(kind='bar', figsize=(10,4), color='steelblue')
plt.title('Cases by Province/State')
plt.tight_layout()
plt.show()

# ===== 3. Victim Age Range ===== ye kari kon kho victim ro neshoun be!!!!!!!!!!
df['Victim Age Range'].value_counts().plot(kind='bar', figsize=(10,4), color='coral')
plt.title('Victim Age Range Distribution')
plt.tight_layout()
plt.show()

# ===== 4. Solicitation Method =====
if 'Solicitation Method' in df.columns:
    df['Solicitation Method'].value_counts().plot(kind='bar', figsize=(10,4), color='mediumseagreen')
    plt.title('Solicitation Method')
    plt.tight_layout()
    plt.show()

# ===== 5. Complaint Type =====
if 'Complaint Type' in df.columns:
    df['Complaint Type'].value_counts().head(10).plot(kind='bar', figsize=(12,4), color='mediumpurple')
    plt.title('Top 10 Complaint Types')
    plt.tight_layout()
    plt.show()

# ===== 6. Dollar Loss by Age Range (Boxplot) =====
plt.figure(figsize=(12,5))
df.dropna(subset=['Victim Age Range', 'Dollar Loss']).boxplot(
    column='Dollar Loss', by='Victim Age Range', figsize=(12,5)
)
plt.title('Dollar Loss by Age Range')
plt.suptitle('')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""# Scatter diagram"""

# #draw histogram of each feature
# df.hist(bins=50, figsize=(20,15))
# #save_fig("attribute_histogram_plots")
# plt.show()

# ===== 7. Full Correlation Heatmap
df_encoded = df.copy()
cat_cols = df_encoded.select_dtypes(include='object').columns

for col in cat_cols:
    df_encoded[col] = pd.factorize(df_encoded[col])[0]

# just numeric columns
numeric_df = df_encoded.select_dtypes(include='number')

plt.figure(figsize=(12,8))
sns.heatmap(numeric_df.corr(), annot=True, fmt='.2f', cmap='coolwarm', linewidths=0.5)
plt.title('Correlation Heatmap - All Features')
plt.tight_layout()
plt.show()

"""## Date Feature Engineering

The `Date Received` column is parsed into structured time-based features:

| Feature | Description |
|---------|-------------|
| `Year` | Year the complaint was filed |
| `Month` | Month (1–12) |
| `DayOfWeek` | Day of week (0=Monday, 6=Sunday) |

These features allow the model to detect seasonal and temporal patterns
in fraud activity.

## Target Variable Engineering — `is_Victim`

The original `Complaint Type` column contains five categories:
`Victim`, `Attempt`, `Other`, `Unknown`, `Incomplete`.

A binary target variable `is_Victim` is created:
- `1` → Victim (complaint resulted in actual fraud)
- `0` → Attempt/Other (fraud was not completed)

**Class Distribution:**
- Victim (1): ~68.4%
- Attempt (0): ~31.6%

This moderate imbalance will be addressed during model training.
##  Missing Value Analysis

Many columns use placeholder strings (e.g., `"Not Available"`,
`"Other/unknown"`) instead of actual `NaN` values.

A custom `analyze_na()` function identifies both real nulls and
NA-like strings for each column, then recommends an action:

- **DROP**: column has > 26% missing → removed entirely
- **fillna**: column has < 26% missing → filled with `'Unknown'`

Result:
- `Solicitation Method` (35.8% missing) → **dropped**
- `Gender` (10.8% missing) → **filled**
- `Victim Age Range` (10.4% missing) → **filled**

"""

print("data set beore encoding:", df.shape)

category_counts = df['Fraud and Cybercrime Thematic Categories'].value_counts().reset_index()
category_counts.columns = ['Category', 'Count']
print(category_counts.to_string(index=False))

category_counts = df['Province/State'].value_counts().reset_index()
category_counts.columns = ['Category', 'Count']
print(category_counts.to_string(index=False))

category_counts = df['Country'].value_counts().reset_index()
category_counts.columns = ['Category', 'Count']
print(category_counts.to_string(index=False))

category_counts = df['Solicitation Method'].value_counts().reset_index()
category_counts.columns = ['Category', 'Count']
print(category_counts.to_string(index=False))

category_counts = df['Language of Correspondence'].value_counts().reset_index()
category_counts.columns = ['Category', 'Count']
print(category_counts.to_string(index=False))

category_counts = df['Victim Age Range'].value_counts().reset_index()
category_counts.columns = ['Category', 'Count']
print(category_counts.to_string(index=False))

category_counts = df['Complaint Type'].value_counts().reset_index()
category_counts.columns = ['Category', 'Count']
print(category_counts.to_string(index=False))

category_counts = df['Dollar Loss'].value_counts().reset_index()
category_counts.columns = ['Category', 'Count']
print(category_counts.to_string(index=False))

df['Date Received'] = pd.to_datetime(
df['Date Received'], errors='coerce')
df['Year']       = df['Date Received'].dt.year
df['Month']      = df['Date Received'].dt.month
df['DayOfWeek']  = df['Date Received'].dt.dayofweek
df['Is_Weekend'] = (df['DayOfWeek'] >= 5).astype(int)

exclude_keywords = ['unknown', 'other', 'incomplete']
df = df[~df['Complaint Type'].astype(str).str.strip().str.lower().apply(
    lambda x: any(kw in x for kw in exclude_keywords)
)]

df['is_Victim'] = df['Complaint Type'].astype(str).str.strip().str.lower().apply(
    lambda x: 1 if any(k in x for k in ['victim', 'victime']) else 0
)

print(df['Complaint Type'].value_counts(dropna=False))
df.drop(columns=['Complaint Type', 'Is_Weekend'], inplace=True)
print(df['is_Victim'].value_counts())

df

def clean_na(df, na_report, protect_cols=None):
    """
    Step 1 — Replace NA-like strings with actual NaN
    Step 2 — Drop rows that have > 1 NA
    Step 3 — fillna remaining (exactly 1 NA):
              categorical → mode
              numeric     → mean
    """
    if protect_cols is None:
        protect_cols = []

    df = df.copy()

    na_map = {
        'Solicitation Method':  ['Other/unknown', 'Not Available'],
        'Gender':               ['Not Available', 'Unknown',
                                 'Prefer not to say', 'Other'],
        'Language':             ['Not Available'],
        'Country':              ['Not Specified'],
        'Province':             ['Not Specified'],
        'Complaint Type':       ['Unknown', 'Incomplete', 'Other'],
        'Victim Age Range':     ['Not Available / non disponible',
                                 'Deceased / Décédé',
                                 'Business / Entreprise'],
    }

    # ── Step 1: Replace NA-like strings with NaN ──────────────────────
    for col, na_vals in na_map.items():
        if col in df.columns:
            df[col] = df[col].replace(na_vals, np.nan)

    # ── Step 2: Drop rows with > 1 NA ─────────────────────────────────
    na_per_row = df.isnull().sum(axis=1)
    rows_to_drop = (na_per_row > 1).sum()
    df = df[na_per_row <= 1].reset_index(drop=True)
    print(f"Dropped {rows_to_drop:,} rows with >1 NA")

    # ── Step 3: fillna remaining (exactly 1 NA per row) ───────────────
    for col in df.columns:
        if df[col].isnull().sum() == 0:
            continue

        if df[col].dtype == 'object':
            fill_val = df[col].mode()[0]
            strategy = 'mode'
        else:
            fill_val = round(df[col].mean(), 2)
            strategy = 'mean'

        n_filled = df[col].isnull().sum()
        df[col] = df[col].fillna(fill_val)
        print(f"  fillna '{col}' → {strategy} = {fill_val}  ({n_filled:,} rows)")

    remaining = df.isnull().sum().sum()
    print(f"\nAfter clean_na: {df.shape} — "
          f"{'no NaN remaining ✓' if remaining == 0 else f'{remaining} NaN left!'}")

    return df

df = clean_na(df, na_report)

df.columns

df

df_encoded = df.copy()
df_encoded = df_encoded.drop(columns=['Number ID', 'Date Received'])
print("encoded data set:", df_encoded.shape)

df_encoded = df.drop(columns=[
    'Number ID',
    'Date Received', 'Number of Victims'
])
# ===== 1. Ordinal Encoding =====
# Victim Age Range
age_order = ['1-9','10-19', '20 - 29', '30 - 39',
             '40 - 49', '50 - 59', '60 - 69', '70 - 79',
             '80 and over', 'Not Available / non disponible']
df_encoded['Victim Age Range'] = df_encoded['Victim Age Range'].map(
    {age: i for i, age in enumerate(age_order)}
).fillna(-1).astype(int)

# Better version (recommended) for One-Hot Encoding
categorical_cols = [
    'Province/State',
    'Fraud and Cybercrime Thematic Categories',
    'Gender',
    'Language of Correspondence',
    'Country', 'Solicitation Method',
    'Complaint Received Type']

df_encoded = pd.get_dummies(df_encoded,
                            columns=categorical_cols,
                            drop_first=True,
                            dtype='int8')   # saves memory

print("After One-Hot Encoding → Shape:", df_encoded.shape)
print("Dtypes:\n", df_encoded.dtypes.value_counts())
df_encoded.head()

# df_encoded.to_csv('your_dataframe.csv', index=False)
# print("DataFrame saved to 'your_dataframe.csv'")

"""## Neural Network (MLP) — Binary Classification

In this section, we apply a **Multilayer Perceptron (MLP)** neural network to classify
whether a fraud complaint results in an actual victim (`is_Victim = 1`) or remains
an attempt (`is_Victim = 0`).

Unlike the regression models used to predict `Dollar Loss`, this is a **binary
classification** task. The MLP is built using Keras (TensorFlow backend) and
incorporates best practices from deep learning:

- **He initialization** for weights (suitable for ELU activation)
- **Batch Normalization** to stabilize and accelerate training
- **ELU activation** to avoid dying neurons
- **Dropout** to prevent overfitting
- **Adam optimizer** with binary cross-entropy loss

### Define Features and Target

The target variable is `is_Victim` (binary: 0 = Attempt, 1 = Victim).

The following columns are excluded from the feature matrix:
- `is_Victim` — this is the target itself
- `Number of Victims` — directly encodes the target (data leakage)
- `Dollar Loss Log` — a derived transformation of Dollar Loss, not needed

`Dollar Loss` is **kept** as a feature, since the reported financial loss
is a valid predictor of whether a complaint was a real fraud or just an attempt.

The dataset is moderately imbalanced: **~68% Victims vs ~32% Attempts**.
This is addressed using class weights in the training step.

### Train / Validation / Test Split (70 / 15 / 15)

The dataset is split into three subsets:
- **Training set (70%)**: used to fit the model
- **Validation set (15%)**: used to tune hyperparameters and monitor early stopping
- **Test set (15%)**: used only at the end for final unbiased evaluation

`stratify=y` ensures that the class ratio (68% / 32%) is preserved in all three
splits, which is critical for imbalanced classification problems.
"""

X = df_encoded.drop(columns=['Dollar Loss', 'is_Victim'])
y = df_encoded['is_Victim']   # 0 = Attempt, 1 = Victim

X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.30, random_state=42, stratify=y
)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.50, random_state=42, stratify=y_temp
)

"""### Feature Scaling

A **MinMaxScaler** is applied to normalize all features to the range [0, 1].
This is important for neural networks because:
- Gradient descent converges faster with normalized inputs
- Features with large ranges would otherwise dominate the learning process

**Important**: the scaler is fit **only on the training set** and then applied
to validation and test sets, preventing any data leakage from future observations.

"""

scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled   = scaler.transform(X_val)
X_test_scaled  = scaler.transform(X_test)

"""### MLP Architecture

The network consists of **3 hidden layers** with decreasing width (256 → 128 → 64),
followed by a single output neuron with a **sigmoid activation** for binary output.

Each hidden layer follows the pattern:

"""

nn_n_inputs = X_train_scaled.shape[1]

nn_model = keras.models.Sequential([
    keras.layers.InputLayer(shape=(nn_n_inputs,)),

    keras.layers.Dense(256, kernel_initializer='he_normal'),
    keras.layers.BatchNormalization(),
    keras.layers.Activation('elu'),
    keras.layers.Dropout(0.3),

    keras.layers.Dense(128, kernel_initializer='he_normal'),
    keras.layers.BatchNormalization(),
    keras.layers.Activation('elu'),
    keras.layers.Dropout(0.3),

    keras.layers.Dense(64, kernel_initializer='he_normal'),
    keras.layers.BatchNormalization(),
    keras.layers.Activation('elu'),
    keras.layers.Dropout(0.2),

    keras.layers.Dense(1, activation='sigmoid')
], name='nn_mlp_classifier')

nn_model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-3),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

nn_model.summary()

"""### Training with Early Stopping

The model is trained for up to **50 epochs** with a batch size of **512**.

**Early Stopping** monitors `val_loss` and halts training if no improvement
is observed for 5 consecutive epochs, then restores the best weights.
This prevents overfitting while reducing unnecessary training time.

Training time is measured using `time.time()` for performance comparison.

"""

nn_start_time = time.time()

nn_early_stop = keras.callbacks.EarlyStopping(
    monitor='val_loss', patience=5, restore_best_weights=True
)

nn_history = nn_model.fit(
    X_train_scaled, y_train,
    validation_data=(X_val_scaled, y_val),
    epochs=30,
    batch_size=512,
    callbacks=[nn_early_stop],
    verbose=1
)

nn_total_time = time.time() - nn_start_time

nn_y_prob_val  = nn_model.predict(X_val_scaled,  verbose=0).ravel()
nn_y_prob_test = nn_model.predict(X_test_scaled, verbose=0).ravel()

nn_y_pred_val  = (nn_y_prob_val  >= 0.5).astype(int)
nn_y_pred_test = (nn_y_prob_test >= 0.5).astype(int)

#  Evaluation: Validation
nn_acc_val  = accuracy_score(y_val,  nn_y_pred_val)
nn_f1_val   = f1_score(y_val,  nn_y_pred_val)
nn_auc_val  = roc_auc_score(y_val,  nn_y_prob_val)

print(f"\n{'='*50}")
print(f"  [NN] VALIDATION SET RESULTS")
print(f"{'='*50}")
print(f"  Accuracy : {nn_acc_val:.4f}")
print(f"  F1-Score : {nn_f1_val:.4f}")
print(f"  AUC-ROC  : {nn_auc_val:.4f}")
print(f"\nConfusion Matrix (Validation):")
print(confusion_matrix(y_val, nn_y_pred_val))

nn_acc_test = accuracy_score(y_test, nn_y_pred_test)
nn_f1_test  = f1_score(y_test, nn_y_pred_test)
nn_auc_test = roc_auc_score(y_test, nn_y_prob_test)

print(f"\n{'='*50}")
print(f"  [NN] TEST SET RESULTS")
print(f"{'='*50}")
print(f"  Accuracy : {nn_acc_test:.4f}")
print(f"  F1-Score : {nn_f1_test:.4f}")
print(f"  AUC-ROC  : {nn_auc_test:.4f}")
print(f"\nConfusion Matrix (Test):")
print(confusion_matrix(y_test, nn_y_pred_test))

"""### Evaluation

The trained model is evaluated separately on the **Validation** and **Test** sets
using three metrics appropriate for binary classification:

| Metric | Why it's used |
|--------|--------------|
| **Accuracy** | Overall percentage of correct predictions |
| **F1-Score** | Balances precision and recall — important for imbalanced data |
| **AUC-ROC** | Measures ranking quality; threshold-independent; ideal for imbalance |

A **Confusion Matrix** is also shown for both sets to visualize false positives
and false negatives separately.

"""

# ── [NN] Final Summary ───────────────────────────────────────────────────────
print(f"\n{'='*50}")
print(f"  [NN] SUMMARY")
print(f"{'='*50}")
print(f"  Training time   : {nn_total_time:.2f}s")
print(f"  {'Metric':<12} {'Val':>8} {'Test':>8}")
print(f"  {'-'*30}")
print(f"  {'Accuracy':<12} {nn_acc_val:>8.4f} {nn_acc_test:>8.4f}")
print(f"  {'F1-Score':<12} {nn_f1_val:>8.4f} {nn_f1_test:>8.4f}")
print(f"  {'AUC-ROC':<12} {nn_auc_val:>8.4f} {nn_auc_test:>8.4f}")
print(f"{'='*50}")

# ── [NN] Learning curves ─────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(12, 4))

axes[0].plot(nn_history.history['loss'],     label='Train Loss')
axes[0].plot(nn_history.history['val_loss'], label='Val Loss')
axes[0].set_title('[NN] Binary Cross-Entropy Loss')
axes[0].set_xlabel('Epoch'); axes[0].legend()

axes[1].plot(nn_history.history['accuracy'],     label='Train Accuracy')
axes[1].plot(nn_history.history['val_accuracy'], label='Val Accuracy')
axes[1].set_title('[NN] Accuracy')
axes[1].set_xlabel('Epoch'); axes[1].legend()

plt.tight_layout()
plt.show()

from sklearn.utils.class_weight import compute_class_weight
import numpy as np

weights = compute_class_weight('balanced',
                               classes=np.array([0, 1]),
                               y=y_train)
cw = {0: weights[0], 1: weights[1]}
print("Class weights:", cw)

"""# Logestic Regression!"""

t0 = time.time()

log_clf = LogisticRegression(
    class_weight="balanced",
    max_iter=1000,
    random_state=42
)

param_grid = {
    "C": [0.01, 0.1, 1, 10],
    "penalty": ["l2"],
    "solver": ["lbfgs", "liblinear"]
}

grid_log = GridSearchCV(
    estimator=log_clf,
    param_grid=param_grid,
    cv=5,
    scoring="f1",
    n_jobs=-1,
    verbose=1
)

grid_log.fit(X_train_scaled, y_train)

best_log = grid_log.best_estimator_

print("Best Params:", grid_log.best_params_)
print("Best CV F1:", grid_log.best_score_)
print(f"Time: {time.time()-t0:.1f}s")

# ===== Validation =====
log_val_pred = best_log.predict(X_val_scaled)
log_val_prob = best_log.predict_proba(X_val_scaled)[:, 1]

print("\n=== Logistic Regression - Validation ===")
print("Accuracy:", accuracy_score(y_val, log_val_pred))
print("F1:", f1_score(y_val, log_val_pred))
print("AUC:", roc_auc_score(y_val, log_val_prob))
print(classification_report(y_val, log_val_pred))

# ===== Test =====
log_test_pred = best_log.predict(X_test_scaled)
log_test_prob = best_log.predict_proba(X_test_scaled)[:, 1]

print("\n=== Logistic Regression - Test ===")
print("Accuracy:", accuracy_score(y_test, log_test_pred))
print("F1:", f1_score(y_test, log_test_pred))
print("AUC:", roc_auc_score(y_test, log_test_prob))
print(classification_report(y_test, log_test_pred))

t0 = time.time()

rf_clf = RandomForestClassifier(
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

rf_param_grid = {
    "n_estimators": [100, 200],
    "max_depth": [10, 20],
    "min_samples_leaf": [1, 2]
}

grid_rf = GridSearchCV(
    estimator=rf_clf,
    param_grid=rf_param_grid,
    cv=5,
    n_jobs=-1,
    verbose=1
)

grid_rf.fit(X_train, y_train)

best_rf = grid_rf.best_estimator_

print("Best Params:", grid_rf.best_params_)
print("Best CV F1:", grid_rf.best_score_)
print(f"Time: {time.time()-t0:.1f}s")

# ===== Validation =====
rf_val_pred = best_rf.predict(X_val_scaled)
rf_val_prob = best_rf.predict_proba(X_val_scaled)[:, 1]

print("\n=== Random Forest - Validation ===")
print("Accuracy:", accuracy_score(y_val, rf_val_pred))
print("F1:", f1_score(y_val, rf_val_pred))
print("AUC:", roc_auc_score(y_val, rf_val_prob))
print(classification_report(y_val, rf_val_pred))

# ===== Test =====
rf_test_pred = best_rf.predict(X_test_scaled)
rf_test_prob = best_rf.predict_proba(X_test_scaled)[:, 1]

print("\n=== Random Forest - Test ===")
print("Accuracy:", accuracy_score(y_test, rf_test_pred))
print("F1:", f1_score(y_test, rf_test_pred))
print("AUC:", roc_auc_score(y_test, rf_test_prob))
print(classification_report(y_test, rf_test_pred))

from xgboost import XGBClassifier
t0 = time.time()


xgb_clf = XGBClassifier(
    random_state=42,
    n_jobs=-1,
)

xgb_param_grid = {
    "n_estimators": [300],
    "max_depth": [3, 5],
    "learning_rate": [0.05, 0.1],

}

grid_xgb = GridSearchCV(
    estimator=xgb_clf,
    param_grid=xgb_param_grid,
    cv=5,
    scoring="f1",
    n_jobs=-1,
    verbose=1
)

grid_xgb.fit(X_train, y_train)

best_xgb = grid_xgb.best_estimator_

print("Best Params:", grid_xgb.best_params_)
print("Best CV F1:", grid_xgb.best_score_)
print(f"Time: {time.time()-t0:.1f}s")

# ===== Validation =====
xgb_val_pred = best_xgb.predict(X_val)
xgb_val_prob = best_xgb.predict_proba(X_val)[:, 1]

print("\n=== XGBoost - Validation ===")
print("Accuracy:", accuracy_score(y_val, xgb_val_pred))
print("F1:", f1_score(y_val, xgb_val_pred))
print("AUC:", roc_auc_score(y_val, xgb_val_prob))
print(classification_report(y_val, xgb_val_pred))

# ===== Test =====
xgb_test_pred = best_xgb.predict(X_test)
xgb_test_prob = best_xgb.predict_proba(X_test)[:, 1]

print("\n=== XGBoost - Test ===")
print("Accuracy:", accuracy_score(y_test, xgb_test_pred))
print("F1:", f1_score(y_test, xgb_test_pred))
print("AUC:", roc_auc_score(y_test, xgb_test_prob))
print(classification_report(y_test, xgb_test_pred))

# import sys
# !{sys.executable} -m pip install xgboost