# -*- coding: utf-8 -*-
"""Term _ Project_ LossCategory.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W39VS0TfPh7syq54a1kPObrszMXGSIr1

# Fraud Loss Severity Classification Using Machine Learning

## Project Overview

In the second phase of this team project, the objective changed from predicting whether an incident involved a victim to classifying the **severity of financial loss** caused by fraud incidents.  

Instead of predicting the exact dollar amount of fraud loss, the goal was to classify incidents into practical risk categories:

- **Low Loss**
- **Medium Loss**
- **High Loss**

This approach created a more realistic business solution and simplified a difficult regression problem into a classification task.



## Business Problem

Organizations often need to prioritize fraud cases quickly. Predicting the exact financial loss is difficult when detailed private customer information is unavailable.  

Therefore, our team focused on building a model that could estimate the likely loss severity category of a fraud incident.

This type of model can help organizations:

- Identify high-risk incidents faster  
- Prioritize investigations  
- Improve fraud response efficiency  
- Support risk management decisions  



## Why Classification Instead of Regression?

During exploratory data analysis, we created a **correlation heatmap** and found that most variables had weak relationships with **Dollar Loss**.  

This was expected because the dataset is public and many sensitive customer-level variables were removed for privacy reasons.

As a result:

- Exact dollar prediction would likely perform poorly  
- Loss category prediction would be more practical and reliable

# Library
"""

import requests
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

from sklearn.model_selection import GridSearchCV

import time
import tensorflow as tf
from tensorflow import keras
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

"""# Importing Dataset"""

# from google.colab import drive
# drive.mount('/content/drive')

df = pd.read_csv("final-Project.csv", on_bad_lines='skip')

"""# PreProcessing

## Initial Exploration

Before any processing, we inspect the structure of the dataset:
- Total rows and columns
- Column names and data types
- Missing value counts

The dataset is **bilingual** (English/French), containing duplicate columns
for most features. French-language duplicates will be removed in the next step.
"""

df.info()

df.isnull().sum()

df.info()

df['Number of Victims / Nombre de victimes'] = df['Number of Victims / Nombre de victimes'].fillna(0).astype(int)
df['Dollar Loss /pertes financières'] = df['Dollar Loss /pertes financières'].replace({r'[$,]': ''}, regex=True).astype(float)
df

df.info()

df.columns

df = df.rename(columns={
    "Numéro d'identification / Number ID": "Number ID",
    "Date Received / Date reçue": "Date Received",
    "Victim Age Range / Tranche d'âge des victimes" : "Victim Age Range",
    "Number of Victims / Nombre de victimes":"Number of Victims",
    "Dollar Loss /pertes financières": "Dollar Loss"
})
display(df.head())

columns_to_drop = [
    'Pays',
    'Genre',
    'Type de plainte',
    'Province/État',
    'Catégories thématiques sur la fraude et la cybercriminalité',
    'Langue de correspondance',
    'Méthode de sollicitation',
    'Type de plainte reçue'
]

existing_columns_to_drop = [col for col in columns_to_drop if col in df.columns]
df = df.drop(columns=existing_columns_to_drop)

display(df.columns)

df['Victim Age Range'] = df['Victim Age Range'].str.lstrip("' ")

df = df[df['Dollar Loss'] > 0]

df

df.info()

df.describe()

#  Dollar Loss Distribution
plt.figure(figsize=(10,4))
df['Dollar Loss'].dropna().hist(bins=50)
plt.title('Distribution of Dollar Loss')
plt.xlabel('Dollar Loss')
plt.show()

#  Top Provinces
df['Province/State'].value_counts().head(10).plot(kind='bar', figsize=(10,4), color='steelblue')
plt.title('Cases by Province/State')
plt.tight_layout()
plt.show()

#  Victim Age Range
df['Victim Age Range'].value_counts().plot(kind='bar', figsize=(10,4), color='coral')
plt.title('Victim Age Range Distribution')
plt.tight_layout()
plt.show()

# Solicitation Method
if 'Solicitation Method' in df.columns:
    df['Solicitation Method'].value_counts().plot(kind='bar', figsize=(10,4), color='mediumseagreen')
    plt.title('Solicitation Method')
    plt.tight_layout()
    plt.show()

#  Complaint Type
if 'Complaint Type' in df.columns:
    df['Complaint Type'].value_counts().head(10).plot(kind='bar', figsize=(12,4), color='mediumpurple')
    plt.title('Top 10 Complaint Types')
    plt.tight_layout()
    plt.show()

# Dollar Loss by Age Range (Boxplot)
plt.figure(figsize=(12,5))
df.dropna(subset=['Victim Age Range', 'Dollar Loss']).boxplot(
    column='Dollar Loss', by='Victim Age Range', figsize=(12,5)
)
plt.title('Dollar Loss by Age Range')
plt.suptitle('')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

df

""" Creating the Target Variable

After filtering the dataset, I created a new target variable called **Loss_Category**.

I divided the non-zero **Dollar Loss** values into three percentile-based groups:

- Lower range → **Low**
- Middle range → **Medium**
- Upper range → **High**

This approach was better than using arbitrary cut-off values because it created more balanced categories based on the actual distribution of the data.

"""

def categorize_loss_percentile(df, column='Dollar Loss'):

    df = df.copy()

    # Check
    if df is None or df.empty:
        print("Empty dataframe")
        df['Loss_Category'] = pd.Series(dtype='object')
        return df

    if column not in df.columns:
        raise KeyError(f"{column} not found")

    # numeric
    df[column] = pd.to_numeric(df[column], errors='coerce')

    valid_values = df[column].dropna()

    if valid_values.empty:
        df['Loss_Category'] = np.nan
        return df


    # Clip outliers

    lower = valid_values.quantile(0.01)
    upper = valid_values.quantile(0.99)

    df[column] = df[column].clip(lower=lower, upper=upper)

    # recompute valid values
    valid_values = df[column].dropna()


    # 3 Quantile bins

    bins = valid_values.quantile([0, 0.33, 0.66, 1.0]).values
    bins = np.unique(bins)

    if len(bins) < 2:
        df['Loss_Category'] = 'Single Value'
        return df

    labels = ['Low', 'Medium', 'High'][:len(bins)-1]

    df['Loss_Category'] = pd.cut(
        df[column],
        bins=bins,
        labels=labels,
        include_lowest=True,
        duplicates='drop'
    )

    return df

df = categorize_loss_percentile(df)
df

print("data set before encoding:", df.shape)

df.info()

category_counts = df['Fraud and Cybercrime Thematic Categories'].value_counts().reset_index()
category_counts.columns = ['Category', 'Count']
print(category_counts.to_string(index=False))

category_counts = df['Province/State'].value_counts().reset_index()
category_counts.columns = ['Category', 'Count']
print(category_counts.to_string(index=False))

category_counts = df['Country'].value_counts().reset_index()
category_counts.columns = ['Category', 'Count']
print(category_counts.to_string(index=False))

category_counts = df['Solicitation Method'].value_counts().reset_index()
category_counts.columns = ['Category', 'Count']
print(category_counts.to_string(index=False))

category_counts = df['Language of Correspondence'].value_counts().reset_index()
category_counts.columns = ['Category', 'Count']
print(category_counts.to_string(index=False))

category_counts = df['Victim Age Range'].value_counts().reset_index()
category_counts.columns = ['Category', 'Count']
print(category_counts.to_string(index=False))

category_counts = df['Complaint Type'].value_counts().reset_index()
category_counts.columns = ['Category', 'Count']
print(category_counts.to_string(index=False))

category_counts = df['Dollar Loss'].value_counts().reset_index()
category_counts.columns = ['Category', 'Count']
print(category_counts.to_string(index=False))

"""## Feature Engineering

To improve the quality of the data, I performed feature engineering.

### Date Features

I used the **Date Received** column to create:

- **Year**
- **Month**
- **Day of Week**

These features allowed the models to learn possible seasonal or time-related fraud patterns.

"""

df['Date Received'] = pd.to_datetime(
df['Date Received'], errors='coerce')
df['Year']       = df['Date Received'].dt.year
df['Month']      = df['Date Received'].dt.month
df['DayOfWeek']  = df['Date Received'].dt.dayofweek
df['Is_Weekend'] = (df['DayOfWeek'] >= 5).astype(int)

df.drop(columns=['Date Received'], inplace=True)

df_pos = df[df['Dollar Loss'] > 0]

# Year
year_med = df_pos.groupby('Year')['Dollar Loss'].median().reset_index()

plt.figure(figsize=(8,5))
sns.barplot(data=year_med, x='Year', y='Dollar Loss')
plt.title("Median Dollar Loss by Year (Positive Cases Only)")
plt.show()

# Month
month_med = df_pos.groupby('Month')['Dollar Loss'].median().reset_index()

plt.figure(figsize=(10,5))
sns.barplot(data=month_med, x='Month', y='Dollar Loss')
plt.title("Median Dollar Loss by Month (Positive Cases Only)")
plt.show()

sns.set_style("whitegrid")


df_pos = df[df['Dollar Loss'] > 0].copy()

# Positive Loss Rate by Year
loss_rate = df.groupby('Year')['Dollar Loss'].apply(lambda x: (x > 0).mean() * 100).reset_index()
loss_rate.columns = ['Year', 'Positive Loss Rate']

plt.figure(figsize=(8,5))
sns.barplot(data=loss_rate, x='Year', y='Positive Loss Rate')
plt.title("Positive Loss Rate by Year (%)")
plt.ylabel("Percent of Cases with Loss")
plt.show()


#  Median Positive Dollar Loss by Year
year_med = df_pos.groupby('Year')['Dollar Loss'].median().reset_index()

plt.figure(figsize=(8,5))
sns.barplot(data=year_med, x='Year', y='Dollar Loss')
plt.title("Median Dollar Loss by Year (Positive Cases Only)")
plt.ylabel("Median Dollar Loss")
plt.show()


#  Total Dollar Loss by Year
year_total = df.groupby('Year')['Dollar Loss'].sum().reset_index()

plt.figure(figsize=(8,5))
sns.barplot(data=year_total, x='Year', y='Dollar Loss')
plt.title("Total Reported Dollar Loss by Year")
plt.ylabel("Total Dollar Loss")
plt.show()


#  Positive Loss Rate by Month
month_rate = df.groupby('Month')['Dollar Loss'].apply(lambda x: (x > 0).mean() * 100).reset_index()
month_rate.columns = ['Month', 'Positive Loss Rate']

plt.figure(figsize=(10,5))
sns.barplot(data=month_rate, x='Month', y='Positive Loss Rate')
plt.title("Positive Loss Rate by Month (%)")
plt.ylabel("Percent of Cases with Loss")
plt.show()


#  Median Positive Dollar Loss by Month
month_med = df_pos.groupby('Month')['Dollar Loss'].median().reset_index()

plt.figure(figsize=(10,5))
sns.barplot(data=month_med, x='Month', y='Dollar Loss')
plt.title("Median Dollar Loss by Month (Positive Cases Only)")
plt.ylabel("Median Dollar Loss")
plt.show()


#  Top 10 Fraud Categories by Total Loss
top_cat = df.groupby('Fraud and Cybercrime Thematic Categories')['Dollar Loss'].sum()
top_cat = top_cat.sort_values(ascending=False).head(10).reset_index()

plt.figure(figsize=(12,6))
sns.barplot(data=top_cat, x='Dollar Loss', y='Fraud and Cybercrime Thematic Categories')
plt.title("Top 10 Fraud Categories by Total Dollar Loss")
plt.xlabel("Total Dollar Loss")
plt.ylabel("")
plt.show()

df.info()

df

"""## Handling Missing Values

Just like in the first project, I handled missing or inconsistent values before training.

Examples included:

- Unknown
- Not specified
- Empty values

I standardized these cases and removed or processed problematic rows when needed. This improved consistency and reduced errors during preprocessing and modeling.

"""

def clean_na(df, na_report= None, protect_cols=None):

    if protect_cols is None:
        protect_cols = []

    df = df.copy()

    na_map = {
        'Solicitation Method':  ['Other/unknown', 'Not Available'],
        'Gender':               ['Not Available', 'Unknown',
                                 'Prefer not to say', 'Other'],
        'Language':             ['Not Available'],
        'Country':              ['Not Specified'],
        'Province':             ['Not Specified'],
        'Complaint Type':       ['Unknown', 'Incomplete', 'Other'],
        'Victim Age Range':     ['Not Available / non disponible',
                                 'Deceased / Décédé',
                                 'Business / Entreprise'],
    }

    # ── Step 1: Replace NA-like strings with NaN ──────────────────────
    for col, na_vals in na_map.items():
        if col in df.columns:
            df[col] = df[col].replace(na_vals, np.nan)

    # ── Step 2: Drop rows with > 1 NA ─────────────────────────────────
    na_per_row = df.isnull().sum(axis=1)
    rows_to_drop = (na_per_row > 1).sum()
    df = df[na_per_row <= 1].reset_index(drop=True)
    print(f"Dropped {rows_to_drop:,} rows with >1 NA")

    # ── Step 3: fillna remaining (exactly 1 NA per row) ───────────────
    for col in df.columns:
        if df[col].isnull().sum() == 0:
            continue

        if df[col].dtype == 'object':
            fill_val = df[col].mode()[0]
            strategy = 'mode'
        else:
            fill_val = round(df[col].mean(), 2)
            strategy = 'mean'

        n_filled = df[col].isnull().sum()
        df[col] = df[col].fillna(fill_val)
        print(f"  fillna '{col}' → {strategy} = {fill_val}  ({n_filled:,} rows)")

    remaining = df.isnull().sum().sum()
    print(f"\nAfter clean_na: {df.shape} — "
          f"{'no NaN remaining ✓' if remaining == 0 else f'{remaining} NaN left!'}")

    return df

df

# exclude_keywords = ['unknown', 'other', 'incomplete']
# df = df[~df['Complaint Type'].astype(str).str.strip().str.lower().apply(
#     lambda x: any(kw in x for kw in exclude_keywords)
# )]

# print(df['Complaint Type'].value_counts(dropna=False))
# df.drop(columns=['Complaint Type'], inplace=True)

# df_encoded['is_Victim'] = df_encoded.loc[df_encoded.index, 'is_Victim']

df = clean_na(df)

df

df = df.drop(columns=['Number ID','Number of Victims', 'Complaint Type','Country','Is_Weekend'])
print("encoded data set:", df.shape)

df

df.columns

"""### Encoding

I encoded the categorical variables as follows:

- **Ordinal Encoding** for **Victim Age Range**
- **One-Hot Encoding** for the other categorical variables

This transformed the data into a numerical format that machine learning models could use.

"""

print("Before encoding shape:", df.shape)

# 1. Clean Victim Age Range
df['Victim Age Range'] = df['Victim Age Range'].astype(str).str.strip()

# 2. Drop rows with 'Not Available / non disponible'
df = df[~df['Victim Age Range'].str.contains('Not Available / non disponible', na=False)].reset_index(drop=True)

print("After dropping Not Available → Shape:", df.shape)

# 3. Proper Ordinal Encoding
age_order = [
    '1 - 9', '10 - 19', '18 - 19', '20 - 29', '30 - 39', '40 - 49',
    '50 - 59', '60 - 69', '70 - 79', '80 and over', '90 - 99', '100 +'
]

age_map = {age: i for i, age in enumerate(age_order)}

df['Victim Age Range Enc'] = df['Victim Age Range'].map(age_map).fillna(len(age_order)).astype(int)

print("Victim Age Range Enc value counts:")
print(df['Victim Age Range Enc'].value_counts().sort_index())

df

# df_encoded.to_csv('your_dataframe.csv', index=False)
# print("DataFrame saved to 'your_dataframe.csv'")

"""## Splitting and Scaling the Data

After cleaning and feature engineering, I divided the dataset into:

- Training set
- Testing set

Then I applied scaling to the numerical features using **MinMaxScaler**.

Scaling was especially useful for models such as:

- Logistic Regression
- SVC
- MLP

because these models are sensitive to feature magnitude.

---

## Model Training

To compare performance, I trained multiple classification models:

### 1. Logistic Regression

### 2. Support Vector Classifier (SVC)

### 3. Random Forest Classifier

### 4. XGBoost

### 5. Multilayer Perceptron (MLP)


"""

df

"""## Avoiding Data Leakage

A very important issue in this project was **data leakage**.

Since **Loss_Category** was created directly from the **Dollar Loss** column, I had to make sure that the original **Dollar Loss** feature was not used as an input during training. Otherwise, the model would effectively see the answer in advance, which would produce misleadingly high performance.

### To avoid this:

- I created **Loss_Category** as the target.
- Then I removed **Dollar Loss** from the feature set before training.

This step was essential for building a valid machine learning pipeline.

"""

drop_cols = ['Loss_Category','Dollar Loss', 'year']
X = df.drop(columns=[c for c in drop_cols if c in df.columns])
y = df['Loss_Category']
print("X shape:", X.shape)
print("y shape:", y.shape)

X_train, X_temp, y_train, y_temp = train_test_split(
    X, y,
    test_size=0.30,
    random_state=42,
    stratify=y
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp,
    test_size=0.50,
    random_state=42,
    stratify=y_temp
)

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

y_train_enc = le.fit_transform(y_train)
y_val_enc   = le.transform(y_val)
y_test_enc  = le.transform(y_test)

"""# Encoding"""

#  select features based on cardinality
low_cardinality = []   # < 10 unique values
high_cardinality = []  # >= 10 unique values

for col in cat_cols:
    n_unique = X_train[col].nunique()
    if n_unique < 10:
        low_cardinality.append(col)
    else:
        high_cardinality.append(col)

print(f"Low cardinality:  {low_cardinality}")   # OneHot
print(f"High cardinality: {high_cardinality}")  # Target Encoding

from sklearn.preprocessing import OneHotEncoder, TargetEncoder

# Identify feature cardinality
cat_cols = X_train.select_dtypes(include='object').columns.tolist()

low_cardinality_cols = []
high_cardinality_cols = []

CARDINALITY_THRESHOLD = 10

for col in cat_cols:
    n_unique = X_train[col].nunique()
    if n_unique < CARDINALITY_THRESHOLD:
        low_cardinality_cols.append(col)
    else:
        high_cardinality_cols.append(col)


print("Feature Encoding Strategy")

print(f"\nLow cardinality features (< {CARDINALITY_THRESHOLD} unique): OneHot Encoding")
for col in low_cardinality_cols:
    print(f"  - {col}: {X_train[col].nunique()} unique values")

print(f"\nHigh cardinality features (>= {CARDINALITY_THRESHOLD} unique): Target Encoding")
for col in high_cardinality_cols:
    print(f"  - {col}: {X_train[col].nunique()} unique values")

# Apply OneHot Encoding to low cardinality features
if low_cardinality_cols:
    onehot_encoder = OneHotEncoder(
        drop='first',
        sparse_output=False,
        handle_unknown='ignore'
    )

    # Fit and transform
    X_train_onehot = onehot_encoder.fit_transform(X_train[low_cardinality_cols])
    X_val_onehot = onehot_encoder.transform(X_val[low_cardinality_cols])
    X_test_onehot = onehot_encoder.transform(X_test[low_cardinality_cols])

    # Get feature names
    onehot_feature_names = onehot_encoder.get_feature_names_out(low_cardinality_cols)

    # Convert to DataFrame
    X_train_onehot_df = pd.DataFrame(
        X_train_onehot,
        columns=onehot_feature_names,
        index=X_train.index
    )
    X_val_onehot_df = pd.DataFrame(
        X_val_onehot,
        columns=onehot_feature_names,
        index=X_val.index
    )
    X_test_onehot_df = pd.DataFrame(
        X_test_onehot,
        columns=onehot_feature_names,
        index=X_test.index
    )
else:
    X_train_onehot_df = pd.DataFrame()
    X_val_onehot_df = pd.DataFrame()
    X_test_onehot_df = pd.DataFrame()

# Apply Target Encoding to high cardinality features
if high_cardinality_cols:
    target_encoder = TargetEncoder(smooth=1.0)

    X_train_target = target_encoder.fit_transform(
        X_train[high_cardinality_cols],
        y_train
    )
    X_val_target = target_encoder.transform(X_val[high_cardinality_cols])
    X_test_target = target_encoder.transform(X_test[high_cardinality_cols])

    # Create proper column names dynamically
    target_col_names = [f"TE_{i}" for i in range(X_train_target.shape[1])]

    X_train_target = pd.DataFrame(
        X_train_target,
        columns=target_col_names,
        index=X_train.index
    )
    X_val_target = pd.DataFrame(
        X_val_target,
        columns=target_col_names,
        index=X_val.index
    )
    X_test_target = pd.DataFrame(
        X_test_target,
        columns=target_col_names,
        index=X_test.index
    )

else:
    X_train_target = pd.DataFrame(index=X_train.index)
    X_val_target = pd.DataFrame(index=X_val.index)
    X_test_target = pd.DataFrame(index=X_test.index)

# Combine all features

# Get numerical columns
num_cols = X_train.select_dtypes(exclude='object').columns.tolist()

# Combine: Numerical + OneHot + Target
X_train_encoded = pd.concat([
    X_train[num_cols].reset_index(drop=True),
    X_train_onehot_df.reset_index(drop=True),
    X_train_target.reset_index(drop=True)
], axis=1)

X_val_encoded = pd.concat([
    X_val[num_cols].reset_index(drop=True),
    X_val_onehot_df.reset_index(drop=True),
    X_val_target.reset_index(drop=True)
], axis=1)

X_test_encoded = pd.concat([
    X_test[num_cols].reset_index(drop=True),
    X_test_onehot_df.reset_index(drop=True),
    X_test_target.reset_index(drop=True)
], axis=1)


print("Encoding Results")

print(f"Original features: {len(cat_cols)} categorical + {len(num_cols)} numerical")
print(f"After encoding: {X_train_encoded.shape[1]} features total")
print(f" Numerical: {len(num_cols)}")
print(f" OneHot encoded: {X_train_onehot_df.shape[1]}")
print(f" Target encoded: {X_train_target.shape[1]}")

# SMOTE
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42, k_neighbors=3)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train_encoded,
    y_train_enc)
print(f"After SMOTE: {X_train_resampled.shape}")

"""# scaled data"""

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()


X_train_scaled = scaler.fit_transform(X_train_resampled)
X_val_scaled = scaler.transform(X_val_encoded)
X_test_scaled = scaler.transform(X_test_encoded)

print(f"Scaled Data Ready:")
print(f"X_train_scaled: {X_train_scaled.shape}")
print(f"X_val_scaled:   {X_val_scaled.shape}")
print(f"X_test_scaled:  {X_test_scaled.shape}")

from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import balanced_accuracy_score, classification_report
import time
start = time.time()

log_reg_grid = LogisticRegression(
    random_state=42,
    max_iter=1000
)

param_grid = {
    'C': [0.1, 1, 10],
    'penalty': [ 'l2'],
    'solver': ['lbfgs'],
    'class_weight': ['balanced']
}

grid_search = GridSearchCV(
    estimator=log_reg_grid,
    param_grid=param_grid,
    cv=5,
    scoring='balanced_accuracy',
    n_jobs=-1
)

grid_search.fit(X_train_scaled, y_train_resampled)

total_time = time.time() - start

print("Best Parameters:")
for param, value in grid_search.best_params_.items():
    print(f"  {param}: {value}")

print(f"\nBest CV Score: {grid_search.best_score_:.4f}")
print(f"Total Time: {total_time/60:.2f} minutes")

best_log_reg = grid_search.best_estimator_
y_pred_best_lr = best_log_reg.predict(X_test_scaled)
test_acc_best_lr = balanced_accuracy_score(y_test_enc, y_pred_best_lr)

print("Final Results :")

print(f"Test Accuracy:  {test_acc_best_lr:.4f}")

print("\nClassification Report:")
print(classification_report(y_test_enc, y_pred_best_lr))

from sklearn.svm import SVC

start = time.time()

svm_grid = SVC(random_state=42, max_iter=2000)

param_grid_svm = {
    'C': [1, 10, 100],
    'gamma': ['scale', 0.01, 0.1],
    'kernel': ['rbf'],
    'class_weight': ['balanced']
}

# GridSearch
grid_svm = GridSearchCV(
    estimator=svm_grid,
    param_grid=param_grid_svm,
    cv=3,
    scoring='accuracy',
    n_jobs=-1,
    verbose=1
)

# Train
grid_svm.fit(X_train_scaled, y_train_resampled)

total_time = time.time() - start


print(" Best Parameters:")
for param, value in grid_svm.best_params_.items():
    print(f"  • {param}: {value}")

best_svm = grid_svm.best_estimator_
y_pred_best_svm = best_svm.predict(X_test_scaled)
test_acc_best_svm = accuracy_score(y_test_enc, y_pred_best_svm)

print(f"\n Best CV Score: {grid_svm.best_score_:.4f}")
print(f"Test Accuracy: {test_acc_best_svm:.4f}")
print(f"Total Time: {total_time/60:.2f} minutes")

print("\nClassification Report:")
print(classification_report(y_test_enc, y_pred_best_svm))

from sklearn.ensemble import RandomForestClassifier

start = time.time()

rf_grid = RandomForestClassifier(random_state=42, n_jobs=-1)

param_grid_rf = {
    'n_estimators': [100, 200],
    'max_depth': [10, 15, 20, None],
    'min_samples_leaf': [5, 10, 20],
    'max_features': ['sqrt', 'log2']
}

grid_rf = GridSearchCV(
    estimator=rf_grid,
    param_grid=param_grid_rf,
    cv=3,
    scoring='balanced_accuracy',
    n_jobs=-1,
    verbose=1
)

grid_rf.fit(X_train_scaled,  y_train_resampled)


total_time = time.time() - start

print("Best Parameters:")
for param, value in grid_rf.best_params_.items():
    print(f"  {param}: {value}")

print(f"Best CV Score: {grid_rf.best_score_:.4f}")
print(f"Total Time: {total_time/60:.2f} minutes")

best_rf = grid_rf.best_estimator_

y_pred_best_rf = best_rf.predict(X_test_scaled)
test_acc_best_rf = balanced_accuracy_score(y_test_enc, y_pred_best_rf)

print("Final Results :")
print(f"Test Accuracy : {test_acc_best_rf:.4f}")

print("Classification Report:")
print(classification_report(y_test_enc, y_pred_best_rf))

from xgboost import XGBClassifier

start = time.time()

xgb_grid = XGBClassifier(random_state=42, n_jobs=-1)

param_grid_xgb = {
    'n_estimators': [200],
    'max_depth': [5, 7],
    'learning_rate': [0.05, 0.1],
    'gamma': [0.1]
}

grid_xgb = GridSearchCV(
    estimator=xgb_grid,
    param_grid=param_grid_xgb,
    cv=3,
    scoring='balanced_accuracy',
    n_jobs=-1,
    verbose=1
)


grid_xgb.fit(X_train_scaled, y_train_resampled)

total_time = time.time() - start

print("Best Parameters:")
for param, value in grid_xgb.best_params_.items():
    print(f"  {param}: {value}")

print(f"Best CV Score: {grid_xgb.best_score_:.4f}")
print(f"Total Time: {total_time/60:.2f} minutes")

best_xgb = grid_xgb.best_estimator_
y_pred_best_xgb = best_xgb.predict(X_test_scaled)
test_acc_best_xgb = balanced_accuracy_score(y_test_enc, y_pred_best_xgb)

print(f"Test Accuracy ): {test_acc_best_xgb:.4f}")

print("Classification Report:")
print(classification_report(y_test_enc, y_pred_best_xgb))

y_train_nn = y_train_resampled
y_val_nn   = y_val_enc
y_test_nn  = y_test_enc

def build_nn_model(units_1=256, units_2=128,
                   dropout_rate=0.3,
                   learning_rate=1e-3,
                   optimizer='adam'):

    model = keras.models.Sequential([
        keras.layers.InputLayer(shape=(nn_n_inputs,)),

        keras.layers.Dense(units_1, kernel_initializer='he_normal'),
        keras.layers.BatchNormalization(),
        keras.layers.Activation('elu'),
        keras.layers.Dropout(dropout_rate),

        keras.layers.Dense(units_2, kernel_initializer='he_normal'),
        keras.layers.BatchNormalization(),
        keras.layers.Activation('elu'),
        keras.layers.Dropout(dropout_rate),

        keras.layers.Dense(64, kernel_initializer='he_normal'),
        keras.layers.BatchNormalization(),
        keras.layers.Activation('elu'),
        keras.layers.Dropout(0.2),

        keras.layers.Dense(nn_n_outputs, activation='softmax')
    ], name='nn_mlp_classifier')

    model.compile(
        optimizer=optimizer,   # ← مستقیم پاس میدی، keras خودش handle میکنه
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )
    return model

import tensorflow as tf
from tensorflow import keras

nn_n_inputs = X_train_scaled.shape[1]
nn_n_outputs = 5

nn_model = keras.models.Sequential([
    keras.layers.InputLayer(shape=(nn_n_inputs,)),

    keras.layers.Dense(256, kernel_initializer='he_normal'),
    keras.layers.BatchNormalization(),
    keras.layers.Activation('elu'),
    keras.layers.Dropout(0.3),

    keras.layers.Dense(128, kernel_initializer='he_normal'),
    keras.layers.BatchNormalization(),
    keras.layers.Activation('relu'),
    keras.layers.Dropout(0.3),

    keras.layers.Dense(64, kernel_initializer='he_normal'),
    keras.layers.BatchNormalization(),
    keras.layers.Activation('elu'),
    keras.layers.Dropout(0.2),

    keras.layers.Dense(nn_n_outputs, activation='softmax')
], name='nn_mlp_classifier')

nn_model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-3),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

nn_model.summary()

nn_start_time = time.time()



nn_history = nn_model.fit(
    X_train_scaled, y_train_resampled.astype(int),
    validation_data=(X_val_scaled, y_val_enc.astype(int)),
    epochs=50,
    batch_size=512,
    verbose=1
)

nn_total_time = time.time() - nn_start_time

from sklearn.metrics import balanced_accuracy_score, classification_report

y_pred_nn = np.argmax(nn_model.predict(X_test_scaled), axis=1)
test_acc_nn = balanced_accuracy_score(y_test_enc, y_pred_nn)

print(f"Test Accuracy: {test_acc_nn:.4f}")
print("Classification Report:")
print(classification_report(y_test_enc, y_pred_nn))

"""# Model Results

After training and testing, I compared the results.

### Final Accuracy Results

- **Random Forest:** 61%
- **MLP:** 60%
- **Logistic Regression:** 59%
- **XGBoost:** 59%
- **SVC:** 50%

Among all models, **Random Forest** achieved the best performance.

"""